// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet.EntityFrameworkCore;

#nullable disable

namespace dotnet.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(dotnetDbContext))]
    [Migration("20231206102347_dailytest5")]
    partial class dailytest5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnet.Domain.CaloriesInfo.CaloriesOfFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("每100克多少热量");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("食物名");

                    b.HasKey("Id");

                    b.ToTable("CaloriesOfFood");
                });

            modelBuilder.Entity("dotnet.Domain.PaymentInfo.singlePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("支出");

                    b.Property<int>("calories")
                        .HasColumnType("int")
                        .HasComment("此顿饭热量是多少");

                    b.Property<bool>("isMeal")
                        .HasColumnType("bit")
                        .HasComment("这顿是否是饭");

                    b.Property<string>("remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("开支内容");

                    b.Property<DateTime>("theTime")
                        .HasColumnType("datetime2")
                        .HasComment("开支时间");

                    b.HasKey("Id");

                    b.ToTable("singlePayment");
                });
#pragma warning restore 612, 618
        }
    }
}
